
services:

  db:
    image: postgres:16.2
    restart: always
    env_file:
      - .env    
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data


  web:
    build: ./code
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env      
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
    volumes:
      - ./code:/code


  nginx:
    image: nginx:1.25.5
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/logs:/var/log/nginx
      - ./code:/code      



volumes:
  postgres_data:
