
services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data


  web:
    container_name: django-filatelie-stafl
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=project_stafl.settingsprod
    depends_on:
      - db
    volumes:
      - ./media:/app/media
      - ./logs/django:/app/logs
      - static:/app/staticfiles 


  nginx:
    build: ./nginx
    volumes:
      - static:/static
      - ./media:/media
      - ./logs/nginx:/var/log/nginx
      - ./certbot/conf:/etc/letsencrypt  # SSL certificates
      - ./certbot/www:/var/www/certbot   # ACME challenge
    ports:
      - "80:80"
      - "443:443"  # Enable HTTPS
    depends_on:
      - web
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot


volumes:
  postgres_data:
  static:
