# Generated by Django 5.1 on 2025-01-12 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkty'},
        ),
    ]
