# Generated by Django 5.1 on 2024-08-31 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Uživatelský profil', 'verbose_name_plural': 'Uživatelské profily'},
        ),
    ]
