# Generated by Django 5.1 on 2025-01-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_profile_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteProduct',
        ),
    ]
