# Generated by Django 5.1 on 2024-09-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_date_of_birth_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='img/blank-profile.jpg', upload_to='users/%Y/%m/%d/', verbose_name='Fotografie'),
        ),
    ]
