# Generated by Django 5.1 on 2025-01-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='img/blank-profile.png', upload_to='users/%Y/%m/%d/', verbose_name='Fotografie'),
        ),
    ]
