# Generated by Django 5.1 on 2025-01-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_favoriteproduct'),
        ('shop', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wishlist',
            field=models.ManyToManyField(to='shop.product', verbose_name='Oblíbené produkty'),
        ),
    ]
